var searchModule = function() {
var idMap = [];
function y(e){idMap.push(e);}
var idx = lunr(function() {
this.field('title', { boost: 10})
this.field('content')
this.field('description', { boost: 5})
this.field('tags', { boost: 50})
this.ref('id')

this.pipeline.remove(lunr.stopWordFilter);
})
function a(e){idx.add(e);}

a({
id:0,
title:"minifyjs",
content:"minifyjs",
description:'',
tags:''
});
a({
id:1,
title:"prepend",
content:"prepend",
description:'',
tags:''
});
a({
id:2,
title:"readfiles",
content:"readfiles",
description:'',
tags:''
});
a({
id:3,
title:"xslt",
content:"xslt",
description:'',
tags:''
});
a({
id:4,
title:"image",
content:"image",
description:'',
tags:''
});
a({
id:5,
title:"groupby",
content:"groupby",
description:'',
tags:''
});
a({
id:6,
title:"concurrenthashset",
content:"concurrenthashset",
description:'',
tags:''
});
a({
id:7,
title:"stringcollectiontextwriter",
content:"stringcollectiontextwriter",
description:'',
tags:''
});
a({
id:8,
title:"pathkind",
content:"pathkind",
description:'',
tags:''
});
a({
id:9,
title:"generatecloudsearchdata",
content:"generatecloudsearchdata",
description:'',
tags:''
});
a({
id:10,
title:"razorcompilationservice",
content:"razorcompilationservice",
description:'',
tags:''
});
a({
id:11,
title:"exitcode",
content:"exitcode",
description:'',
tags:''
});
a({
id:12,
title:"filename",
content:"filename",
description:'',
tags:''
});
a({
id:13,
title:"idocument",
content:"idocument",
description:'',
tags:''
});
a({
id:14,
title:"wyamsettings",
content:"wyamsettings",
description:'',
tags:''
});
a({
id:15,
title:"testfile",
content:"testfile",
description:'',
tags:''
});
a({
id:16,
title:"nugetsourcesettings",
content:"nugetsourcesettings",
description:'',
tags:''
});
a({
id:17,
title:"ifileprovidercollection",
content:"ifileprovidercollection",
description:'',
tags:''
});
a({
id:18,
title:"moduleextensions",
content:"moduleextensions",
description:'',
tags:''
});
a({
id:19,
title:"requestheader",
content:"requestheader",
description:'',
tags:''
});
a({
id:20,
title:"sidecar",
content:"sidecar",
description:'',
tags:''
});
a({
id:21,
title:"countmodule",
content:"countmodule",
description:'',
tags:''
});
a({
id:22,
title:"copymeta",
content:"copymeta",
description:'',
tags:''
});
a({
id:23,
title:"metadataitems",
content:"metadataitems",
description:'',
tags:''
});
a({
id:24,
title:"branch",
content:"branch",
description:'',
tags:''
});
a({
id:25,
title:"irazorviewengine",
content:"irazorviewengine",
description:'',
tags:''
});
a({
id:26,
title:"documentconfig",
content:"documentconfig",
description:'',
tags:''
});
a({
id:27,
title:"inamespacescollection",
content:"inamespacescollection",
description:'',
tags:''
});
a({
id:28,
title:"index",
content:"index",
description:'',
tags:''
});
a({
id:29,
title:"confighelper",
content:"confighelper",
description:'',
tags:''
});
a({
id:30,
title:"cacheddelegatemetadatavalue",
content:"cacheddelegatemetadatavalue",
description:'',
tags:''
});
a({
id:31,
title:"ifilesystem",
content:"ifilesystem",
description:'',
tags:''
});
a({
id:32,
title:"gitkeys",
content:"gitkeys",
description:'',
tags:''
});
a({
id:33,
title:"testdocument",
content:"testdocument",
description:'',
tags:''
});
a({
id:34,
title:"rantmodule",
content:"rantmodule",
description:'',
tags:''
});
a({
id:35,
title:"viewengineresult",
content:"viewengineresult",
description:'',
tags:''
});
a({
id:36,
title:"foreach",
content:"foreach",
description:'',
tags:''
});
a({
id:37,
title:"codeanalysiskeys",
content:"codeanalysiskeys",
description:'',
tags:''
});
a({
id:38,
title:"switch",
content:"switch",
description:'',
tags:''
});
a({
id:39,
title:"iindentedtraceevent",
content:"iindentedtraceevent",
description:'',
tags:''
});
a({
id:40,
title:"ifileprovider",
content:"ifileprovider",
description:'',
tags:''
});
a({
id:41,
title:"iviewstartprovider",
content:"iviewstartprovider",
description:'',
tags:''
});
a({
id:42,
title:"engine",
content:"engine",
description:'',
tags:''
});
a({
id:43,
title:"content",
content:"content",
description:'',
tags:''
});
a({
id:44,
title:"globalmetadataparser",
content:"globalmetadataparser",
description:'',
tags:''
});
a({
id:45,
title:"attributevalue",
content:"attributevalue",
description:'',
tags:''
});
a({
id:46,
title:"ifile",
content:"ifile",
description:'',
tags:''
});
a({
id:47,
title:"viewcontext",
content:"viewcontext",
description:'',
tags:''
});
a({
id:48,
title:"excerpt",
content:"excerpt",
description:'',
tags:''
});
a({
id:49,
title:"gitmodule",
content:"gitmodule",
description:'',
tags:''
});
a({
id:50,
title:"where",
content:"where",
description:'',
tags:''
});
a({
id:51,
title:"configurator",
content:"configurator",
description:'',
tags:''
});
a({
id:52,
title:"isettings",
content:"isettings",
description:'',
tags:''
});
a({
id:53,
title:"searchindexkeys",
content:"searchindexkeys",
description:'',
tags:''
});
a({
id:54,
title:"renderasyncdelegate",
content:"renderasyncdelegate",
description:'',
tags:''
});
a({
id:55,
title:"iview",
content:"iview",
description:'',
tags:''
});
a({
id:56,
title:"readworkspace",
content:"readworkspace",
description:'',
tags:''
});
a({
id:57,
title:"basefixture",
content:"basefixture",
description:'',
tags:''
});
a({
id:58,
title:"validatemeta",
content:"validatemeta",
description:'',
tags:''
});
a({
id:59,
title:"metadataitem",
content:"metadataitem",
description:'',
tags:''
});
a({
id:60,
title:"modulecollection",
content:"modulecollection",
description:'',
tags:''
});
a({
id:61,
title:"generatecontent",
content:"generatecontent",
description:'',
tags:''
});
a({
id:62,
title:"concat",
content:"concat",
description:'',
tags:''
});
a({
id:63,
title:"htmlescape",
content:"htmlescape",
description:'',
tags:''
});
a({
id:64,
title:"imageinstruction",
content:"imageinstruction",
description:'',
tags:''
});
a({
id:65,
title:"globber",
content:"globber",
description:'',
tags:''
});
a({
id:66,
title:"packageinstaller",
content:"packageinstaller",
description:'',
tags:''
});
a({
id:67,
title:"ipreprocessor",
content:"ipreprocessor",
description:'',
tags:''
});
a({
id:68,
title:"razorview",
content:"razorview",
description:'',
tags:''
});
a({
id:69,
title:"contentmodule",
content:"contentmodule",
description:'',
tags:''
});
a({
id:70,
title:"minifycss",
content:"minifycss",
description:'',
tags:''
});
a({
id:71,
title:"ipipelinecollection",
content:"ipipelinecollection",
description:'',
tags:''
});
a({
id:72,
title:"rss",
content:"rss",
description:'',
tags:''
});
a({
id:73,
title:"directoryequalitycomparer",
content:"directoryequalitycomparer",
description:'',
tags:''
});
a({
id:74,
title:"imetadatadictionary",
content:"imetadatadictionary",
description:'',
tags:''
});
a({
id:75,
title:"generatejson",
content:"generatejson",
description:'',
tags:''
});
a({
id:76,
title:"markdown",
content:"markdown",
description:'',
tags:''
});
a({
id:77,
title:"classcatalog",
content:"classcatalog",
description:'',
tags:''
});
a({
id:78,
title:"json",
content:"json",
description:'',
tags:''
});
a({
id:79,
title:"if",
content:"if",
description:'',
tags:''
});
a({
id:80,
title:"dynamicviewdata",
content:"dynamicviewdata",
description:'',
tags:''
});
a({
id:81,
title:"directorymeta",
content:"directorymeta",
description:'',
tags:''
});
a({
id:82,
title:"autolink",
content:"autolink",
description:'',
tags:''
});
a({
id:83,
title:"extensionlessurlsoptions",
content:"extensionlessurlsoptions",
description:'',
tags:''
});
a({
id:84,
title:"ireadonlysettings",
content:"ireadonlysettings",
description:'',
tags:''
});
a({
id:85,
title:"concatbranch",
content:"concatbranch",
description:'',
tags:''
});
a({
id:86,
title:"unwrittenfiles",
content:"unwrittenfiles",
description:'',
tags:''
});
a({
id:87,
title:"paginate",
content:"paginate",
description:'',
tags:''
});
a({
id:88,
title:"wyamaliases",
content:"wyamaliases",
description:'',
tags:''
});
a({
id:89,
title:"append",
content:"append",
description:'',
tags:''
});
a({
id:90,
title:"customdocumentfactory",
content:"customdocumentfactory",
description:'',
tags:''
});
a({
id:91,
title:"gitcommits",
content:"gitcommits",
description:'',
tags:''
});
a({
id:92,
title:"iexecutioncache",
content:"iexecutioncache",
description:'',
tags:''
});
a({
id:93,
title:"documents",
content:"documents",
description:'',
tags:''
});
a({
id:94,
title:"xmp",
content:"xmp",
description:'',
tags:''
});
a({
id:95,
title:"sitemapitem",
content:"sitemapitem",
description:'',
tags:''
});
a({
id:96,
title:"readproject",
content:"readproject",
description:'',
tags:''
});
a({
id:97,
title:"positiontagged",
content:"positiontagged",
description:'',
tags:''
});
a({
id:98,
title:"idocumentcollection",
content:"idocumentcollection",
description:'',
tags:''
});
a({
id:99,
title:"virtualpathrazorpagefactory",
content:"virtualpathrazorpagefactory",
description:'',
tags:''
});
a({
id:100,
title:"bufferedhtmlcontent",
content:"bufferedhtmlcontent",
description:'',
tags:''
});
a({
id:101,
title:"wyamstreamfileprovider",
content:"wyamstreamfileprovider",
description:'',
tags:''
});
a({
id:102,
title:"readsolution",
content:"readsolution",
description:'',
tags:''
});
a({
id:103,
title:"htmlquery",
content:"htmlquery",
description:'',
tags:''
});
a({
id:104,
title:"htmlhelper",
content:"htmlhelper",
description:'',
tags:''
});
a({
id:105,
title:"meta",
content:"meta",
description:'',
tags:''
});
a({
id:106,
title:"minifyxml",
content:"minifyxml",
description:'',
tags:''
});
a({
id:107,
title:"writefiles",
content:"writefiles",
description:'',
tags:''
});
a({
id:108,
title:"configscriptbase",
content:"configscriptbase",
description:'',
tags:''
});
a({
id:109,
title:"irazorpagefactory",
content:"irazorpagefactory",
description:'',
tags:''
});
a({
id:110,
title:"idirective",
content:"idirective",
description:'',
tags:''
});
a({
id:111,
title:"github",
content:"github",
description:'',
tags:''
});
a({
id:112,
title:"delegatemetadatavalue",
content:"delegatemetadatavalue",
description:'',
tags:''
});
a({
id:113,
title:"assemblyloader",
content:"assemblyloader",
description:'',
tags:''
});
a({
id:114,
title:"viewdatadictionary",
content:"viewdatadictionary",
description:'',
tags:''
});
a({
id:115,
title:"wyamrunner",
content:"wyamrunner",
description:'',
tags:''
});
a({
id:116,
title:"imvcrazorhost",
content:"imvcrazorhost",
description:'',
tags:''
});
a({
id:117,
title:"collectionextensions",
content:"collectionextensions",
description:'',
tags:''
});
a({
id:118,
title:"mvcrazorhost",
content:"mvcrazorhost",
description:'',
tags:''
});
a({
id:119,
title:"take",
content:"take",
description:'',
tags:''
});
a({
id:120,
title:"ihtmlcontent",
content:"ihtmlcontent",
description:'',
tags:''
});
a({
id:121,
title:"generatemeta",
content:"generatemeta",
description:'',
tags:''
});
a({
id:122,
title:"filepath",
content:"filepath",
description:'',
tags:''
});
a({
id:123,
title:"baserazorpage",
content:"baserazorpage",
description:'',
tags:''
});
a({
id:124,
title:"othercomment",
content:"othercomment",
description:'',
tags:''
});
a({
id:125,
title:"anchorposition",
content:"anchorposition",
description:'',
tags:''
});
a({
id:126,
title:"interlockedbool",
content:"interlockedbool",
description:'',
tags:''
});
a({
id:127,
title:"contextconfig",
content:"contextconfig",
description:'',
tags:''
});
a({
id:128,
title:"razorpageresult",
content:"razorpageresult",
description:'',
tags:''
});
a({
id:129,
title:"searchindex",
content:"searchindex",
description:'',
tags:''
});
a({
id:130,
title:"exceltocsv",
content:"exceltocsv",
description:'',
tags:''
});
a({
id:131,
title:"pathequalitycomparer",
content:"pathequalitycomparer",
description:'',
tags:''
});
a({
id:132,
title:"razorfilehash",
content:"razorfilehash",
description:'',
tags:''
});
a({
id:133,
title:"customdocument",
content:"customdocument",
description:'',
tags:''
});
a({
id:134,
title:"yaml",
content:"yaml",
description:'',
tags:''
});
a({
id:135,
title:"less",
content:"less",
description:'',
tags:''
});
a({
id:136,
title:"pathcollection",
content:"pathcollection",
description:'',
tags:''
});
a({
id:137,
title:"extensionlessurlsextensions",
content:"extensionlessurlsextensions",
description:'',
tags:''
});
a({
id:138,
title:"imodule",
content:"imodule",
description:'',
tags:''
});
a({
id:139,
title:"typehelper",
content:"typehelper",
description:'',
tags:''
});
a({
id:140,
title:"localfileprovider",
content:"localfileprovider",
description:'',
tags:''
});
a({
id:141,
title:"relativefileinfo",
content:"relativefileinfo",
description:'',
tags:''
});
a({
id:142,
title:"minifyhtml",
content:"minifyhtml",
description:'',
tags:''
});
a({
id:143,
title:"imetadata",
content:"imetadata",
description:'',
tags:''
});
a({
id:144,
title:"ireadonlyfilesystem",
content:"ireadonlyfilesystem",
description:'',
tags:''
});
a({
id:145,
title:"searchindexitem",
content:"searchindexitem",
description:'',
tags:''
});
a({
id:146,
title:"documentcollectionextensions",
content:"documentcollectionextensions",
description:'',
tags:''
});
a({
id:147,
title:"combine",
content:"combine",
description:'',
tags:''
});
a({
id:148,
title:"trace",
content:"trace",
description:'',
tags:''
});
a({
id:149,
title:"assemblynamesettings",
content:"assemblynamesettings",
description:'',
tags:''
});
a({
id:150,
title:"imagefilter",
content:"imagefilter",
description:'',
tags:''
});
a({
id:151,
title:"metadataparseexception",
content:"metadataparseexception",
description:'',
tags:''
});
a({
id:152,
title:"stringbuilderstream",
content:"stringbuilderstream",
description:'',
tags:''
});
a({
id:153,
title:"orderby",
content:"orderby",
description:'',
tags:''
});
a({
id:154,
title:"execute",
content:"execute",
description:'',
tags:''
});
a({
id:155,
title:"program",
content:"program",
description:'',
tags:''
});
a({
id:156,
title:"helperresult",
content:"helperresult",
description:'',
tags:''
});
a({
id:157,
title:"iviewengine",
content:"iviewengine",
description:'',
tags:''
});
a({
id:158,
title:"idocumentfactory",
content:"idocumentfactory",
description:'',
tags:''
});
a({
id:159,
title:"ifilesystementry",
content:"ifilesystementry",
description:'',
tags:''
});
a({
id:160,
title:"normalizedpath",
content:"normalizedpath",
description:'',
tags:''
});
a({
id:161,
title:"viewhierarchyutility",
content:"viewhierarchyutility",
description:'',
tags:''
});
a({
id:162,
title:"replacein",
content:"replacein",
description:'',
tags:''
});
a({
id:163,
title:"imetadata",
content:"imetadata",
description:'',
tags:''
});
a({
id:164,
title:"tree",
content:"tree",
description:'',
tags:''
});
a({
id:165,
title:"ipipeline",
content:"ipipeline",
description:'',
tags:''
});
a({
id:166,
title:"razorviewengine",
content:"razorviewengine",
description:'',
tags:''
});
a({
id:167,
title:"wyamfileprovider",
content:"wyamfileprovider",
description:'',
tags:''
});
a({
id:168,
title:"razorviewfactory",
content:"razorviewfactory",
description:'',
tags:''
});
a({
id:169,
title:"imetadatavalue",
content:"imetadatavalue",
description:'',
tags:''
});
a({
id:170,
title:"minifierbase",
content:"minifierbase",
description:'',
tags:''
});
a({
id:171,
title:"download",
content:"download",
description:'',
tags:''
});
a({
id:172,
title:"changefrequency",
content:"changefrequency",
description:'',
tags:''
});
a({
id:173,
title:"gitcontributors",
content:"gitcontributors",
description:'',
tags:''
});
a({
id:174,
title:"idirectory",
content:"idirectory",
description:'',
tags:''
});
a({
id:175,
title:"keys",
content:"keys",
description:'',
tags:''
});
a({
id:176,
title:"copyfiles",
content:"copyfiles",
description:'',
tags:''
});
a({
id:177,
title:"clisupport",
content:"clisupport",
description:'',
tags:''
});
a({
id:178,
title:"preprocessor",
content:"preprocessor",
description:'',
tags:''
});
a({
id:179,
title:"irazorcompilationservice",
content:"irazorcompilationservice",
description:'',
tags:''
});
a({
id:180,
title:"crc",
content:"crc",
description:'',
tags:''
});
a({
id:181,
title:"configextensions",
content:"configextensions",
description:'',
tags:''
});
a({
id:182,
title:"viewstartprovider",
content:"viewstartprovider",
description:'',
tags:''
});
a({
id:183,
title:"sitemap",
content:"sitemap",
description:'',
tags:''
});
a({
id:184,
title:"replace",
content:"replace",
description:'',
tags:''
});
a({
id:185,
title:"fileinfoextensions",
content:"fileinfoextensions",
description:'',
tags:''
});
a({
id:186,
title:"fileequalitycomparer",
content:"fileequalitycomparer",
description:'',
tags:''
});
a({
id:187,
title:"htmlhelperpartialextensions",
content:"htmlhelperpartialextensions",
description:'',
tags:''
});
a({
id:188,
title:"frontmatter",
content:"frontmatter",
description:'',
tags:''
});
a({
id:189,
title:"irazorpage",
content:"irazorpage",
description:'',
tags:''
});
a({
id:190,
title:"assemblysettings",
content:"assemblysettings",
description:'',
tags:''
});
a({
id:191,
title:"htmlstring",
content:"htmlstring",
description:'',
tags:''
});
a({
id:192,
title:"directorypath",
content:"directorypath",
description:'',
tags:''
});
a({
id:193,
title:"ireadonlypipeline",
content:"ireadonlypipeline",
description:'',
tags:''
});
a({
id:194,
title:"readapplicationinput",
content:"readapplicationinput",
description:'',
tags:''
});
a({
id:195,
title:"minifyxhtml",
content:"minifyxhtml",
description:'',
tags:''
});
a({
id:196,
title:"merge",
content:"merge",
description:'',
tags:''
});
a({
id:197,
title:"iassemblycollection",
content:"iassemblycollection",
description:'',
tags:''
});
a({
id:198,
title:"trace",
content:"trace",
description:'',
tags:''
});
a({
id:199,
title:"razorpage",
content:"razorpage",
description:'',
tags:''
});
a({
id:200,
title:"irawassemblycollection",
content:"irawassemblycollection",
description:'',
tags:''
});
a({
id:201,
title:"csvtohtml",
content:"csvtohtml",
description:'',
tags:''
});
a({
id:202,
title:"extensionlessurlsmiddleware",
content:"extensionlessurlsmiddleware",
description:'',
tags:''
});
a({
id:203,
title:"iexecutioncontext",
content:"iexecutioncontext",
description:'',
tags:''
});
a({
id:204,
title:"ireadonlyfileprovidercollection",
content:"ireadonlyfileprovidercollection",
description:'',
tags:''
});
a({
id:205,
title:"hueinstruction",
content:"hueinstruction",
description:'',
tags:''
});
a({
id:206,
title:"directivevalue",
content:"directivevalue",
description:'',
tags:''
});
a({
id:207,
title:"referencecomment",
content:"referencecomment",
description:'',
tags:''
});
a({
id:208,
title:"testtracelistener",
content:"testtracelistener",
description:'',
tags:''
});
a({
id:209,
title:"actionfilesystemwatcher",
content:"actionfilesystemwatcher",
description:'',
tags:''
});
a({
id:210,
title:"irazorviewfactory",
content:"irazorviewfactory",
description:'',
tags:''
});
a({
id:211,
title:"testdirectory",
content:"testdirectory",
description:'',
tags:''
});
a({
id:212,
title:"testfileprovider",
content:"testfileprovider",
description:'',
tags:''
});
a({
id:213,
title:"analyzecsharp",
content:"analyzecsharp",
description:'',
tags:''
});
a({
id:214,
title:"iasnewdocuments",
content:"iasnewdocuments",
description:'',
tags:''
});
a({
id:215,
title:"itrace",
content:"itrace",
description:'',
tags:''
});
a({
id:216,
title:"nugetsettings",
content:"nugetsettings",
description:'',
tags:''
});
a({
id:217,
title:"razor",
content:"razor",
description:'',
tags:''
});
y({
url:'/api/Wyam.Minification/431A35FB',
title:"MinifyJs",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/F5ECB8B6',
title:"Prepend",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/C5A656EF',
title:"ReadFiles",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Templates/4B48616B',
title:"Xslt",
description:""
});
y({
url:'/api/Wyam.Images/2520F667',
title:"Image",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/709AAAA5',
title:"GroupBy",
description:""
});
y({
url:'/api/Wyam.Common.Util/07FDBB74',
title:"ConcurrentHashSet<T>",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/FD155592',
title:"StringCollectionTextWriter",
description:""
});
y({
url:'/api/Wyam.Common.IO/B9B7F85C',
title:"PathKind",
description:""
});
y({
url:'/api/Wyam.AmazonWebServices/6EA2A85E',
title:"GenerateCloudSearchData",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor.Compilation/5B233968',
title:"RazorCompilationService",
description:""
});
y({
url:'/api/Wyam/3E038DF3',
title:"ExitCode",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/0F4CA627',
title:"FileName",
description:""
});
y({
url:'/api/Wyam.Common.Documents/F359E898',
title:"IDocument",
description:""
});
y({
url:'/api/Cake.Wyam/0DA860B8',
title:"WyamSettings",
description:""
});
y({
url:'/api/Wyam.Testing.IO/55EE11A2',
title:"TestFile",
description:""
});
y({
url:'/api/Cake.Wyam/C5F9D6E6',
title:"NuGetSourceSettings",
description:""
});
y({
url:'/api/Wyam.Common.IO/4B5BECA2',
title:"IFileProviderCollection",
description:""
});
y({
url:'/api/Wyam.Core.Modules/730E2B24',
title:"ModuleExtensions",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/52828D3B',
title:"RequestHeader",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/BB05F84F',
title:"Sidecar",
description:""
});
y({
url:'/api/Wyam.Testing.Modules/EC91E274',
title:"CountModule",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/01A54354',
title:"CopyMeta",
description:""
});
y({
url:'/api/Wyam.Common.Meta/FBA8D7C9',
title:"MetadataItems",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/2D4970B5',
title:"Branch",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/1C9EF641',
title:"IRazorViewEngine",
description:""
});
y({
url:'/api/Wyam.Common.Configuration/10CB7479',
title:"DocumentConfig",
description:""
});
y({
url:'/api/Wyam.Core.Configuration/BD6A1E02',
title:"INamespacesCollection",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/78768B35',
title:"Index",
description:""
});
y({
url:'/api/Wyam.Common.Configuration/36C201E7',
title:"ConfigHelper<T>",
description:""
});
y({
url:'/api/Wyam.Common.Meta/B2F39640',
title:"CachedDelegateMetadataValue",
description:""
});
y({
url:'/api/Wyam.Common.IO/8E17CFD1',
title:"IFileSystem",
description:""
});
y({
url:'/api/Wyam.Git/69C70F1B',
title:"GitKeys",
description:""
});
y({
url:'/api/Wyam.Testing.Documents/E2E28DED',
title:"TestDocument",
description:""
});
y({
url:'/api/Wyam.TextGeneration/51AFD101',
title:"RantModule",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/CBAC207B',
title:"ViewEngineResult",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/45D7052F',
title:"ForEach",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/E793BC90',
title:"CodeAnalysisKeys",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/2A191F61',
title:"Switch",
description:""
});
y({
url:'/api/Wyam.Common.Tracing/51754161',
title:"IIndentedTraceEvent",
description:""
});
y({
url:'/api/Wyam.Common.IO/6E3AD006',
title:"IFileProvider",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/AE708F89',
title:"IViewStartProvider",
description:""
});
y({
url:'/api/Wyam.Core.Execution/3C35E625',
title:"Engine",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/C1CDC3BA',
title:"Content",
description:""
});
y({
url:'/api/Wyam/B2248776',
title:"GlobalMetadataParser",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/236F3C9C',
title:"AttributeValue",
description:""
});
y({
url:'/api/Wyam.Common.IO/62D4421F',
title:"IFile",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc/F6823FFC',
title:"ViewContext",
description:""
});
y({
url:'/api/Wyam.Html/69EB84EB',
title:"Excerpt",
description:""
});
y({
url:'/api/Wyam.Git/3D37613E',
title:"GitModule",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/4E935530',
title:"Where",
description:""
});
y({
url:'/api/Wyam.Configuration/78A82B92',
title:"Configurator",
description:""
});
y({
url:'/api/Wyam.Common.Configuration/32EB6F46',
title:"ISettings",
description:""
});
y({
url:'/api/Wyam.SearchIndex/E925646A',
title:"SearchIndexKeys",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/D29673F1',
title:"RenderAsyncDelegate",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/DDEBFAEE',
title:"IView",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/1CC21195',
title:"ReadWorkspace",
description:""
});
y({
url:'/api/Wyam.Testing/AC156918',
title:"BaseFixture",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/9368CAFE',
title:"ValidateMeta<T>",
description:""
});
y({
url:'/api/Wyam.Common.Meta/260DE2D4',
title:"MetadataItem",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/528574FD',
title:"ModuleCollection",
description:""
});
y({
url:'/api/Wyam.TextGeneration/3FEBE677',
title:"GenerateContent",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/7374D090',
title:"Concat",
description:""
});
y({
url:'/api/Wyam.Html/D80423B4',
title:"HtmlEscape",
description:""
});
y({
url:'/api/Wyam.Images/765D727A',
title:"ImageInstruction",
description:""
});
y({
url:'/api/Wyam.Core.IO.Globbing/9A9A5AE2',
title:"Globber",
description:""
});
y({
url:'/api/Wyam.Configuration.NuGet/A8AF66DE',
title:"PackageInstaller",
description:""
});
y({
url:'/api/Wyam.Configuration.Preprocessing/9BC18C2B',
title:"IPreprocessor",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/F95A27B7',
title:"RazorView",
description:""
});
y({
url:'/api/Wyam.Common.Modules/035B5B42',
title:"ContentModule",
description:""
});
y({
url:'/api/Wyam.Minification/B4D1F1FB',
title:"MinifyCss",
description:""
});
y({
url:'/api/Wyam.Common.Execution/13816118',
title:"IPipelineCollection",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/B7655D44',
title:"Rss",
description:""
});
y({
url:'/api/Wyam.Common.IO/712BD29F',
title:"DirectoryEqualityComparer",
description:""
});
y({
url:'/api/Wyam.Common.Meta/AD3B6C7E',
title:"IMetadataDictionary",
description:""
});
y({
url:'/api/Wyam.Json/2E06486E',
title:"GenerateJson",
description:""
});
y({
url:'/api/Wyam.Markdown/005E6EC2',
title:"Markdown",
description:""
});
y({
url:'/api/Wyam.Configuration.Assemblies/4755BF14',
title:"ClassCatalog",
description:""
});
y({
url:'/api/Wyam.Json/B5451CEF',
title:"Json",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/B5BA6847',
title:"If",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/E0F9D563',
title:"DynamicViewData",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/60D1B362',
title:"DirectoryMeta",
description:""
});
y({
url:'/api/Wyam.Html/44A2373E',
title:"AutoLink",
description:""
});
y({
url:'/api/Wyam.Owin/E4F34773',
title:"ExtensionlessUrlsOptions",
description:""
});
y({
url:'/api/Wyam.Common.Configuration/231ED196',
title:"IReadOnlySettings",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/202689E6',
title:"ConcatBranch",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/59667BEB',
title:"UnwrittenFiles",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/2B4112E9',
title:"Paginate",
description:""
});
y({
url:'/api/Cake.Wyam/C3710112',
title:"WyamAliases",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/C0CCEA1D',
title:"Append",
description:""
});
y({
url:'/api/Wyam.Core.Documents/C8D42587',
title:"CustomDocumentFactory<T>",
description:""
});
y({
url:'/api/Wyam.Git/8A65C8DE',
title:"GitCommits",
description:""
});
y({
url:'/api/Wyam.Common.Caching/17C8DD70',
title:"IExecutionCache",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/872B0C59',
title:"Documents",
description:""
});
y({
url:'/api/Wyam.Xmp/2C88D59F',
title:"Xmp",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/EBCFE23E',
title:"SitemapItem",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/C2E4AD72',
title:"ReadProject",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/F25E819E',
title:"PositionTagged<T>",
description:""
});
y({
url:'/api/Wyam.Common.Documents/DAA0881A',
title:"IDocumentCollection",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/8ADF0F0B',
title:"VirtualPathRazorPageFactory",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/8C25D568',
title:"BufferedHtmlContent",
description:""
});
y({
url:'/api/Wyam.Razor/E063FFB8',
title:"WyamStreamFileProvider",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/0C5BB6AD',
title:"ReadSolution",
description:""
});
y({
url:'/api/Wyam.Html/A574658B',
title:"HtmlQuery",
description:""
});
y({
url:'/api/Wyam.Razor/C3A2D549',
title:"HtmlHelper",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/885C2CFF',
title:"Meta",
description:""
});
y({
url:'/api/Wyam.Minification/0FAFCBB2',
title:"MinifyXml",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/327D628C',
title:"WriteFiles",
description:""
});
y({
url:'/api/Wyam.Configuration.ConfigScript/1E54DF92',
title:"ConfigScriptBase",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/C8779D97',
title:"IRazorPageFactory",
description:""
});
y({
url:'/api/Wyam.Configuration.Preprocessing/B46E9F9D',
title:"IDirective",
description:""
});
y({
url:'/api/Wyam.GitHub/D0CA856F',
title:"GitHub",
description:""
});
y({
url:'/api/Wyam.Common.Meta/4854B78E',
title:"DelegateMetadataValue",
description:""
});
y({
url:'/api/Wyam.Configuration.Assemblies/5AC92CDF',
title:"AssemblyLoader",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc/71970667',
title:"ViewDataDictionary",
description:""
});
y({
url:'/api/Cake.Wyam/5E298058',
title:"WyamRunner",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/09D5F716',
title:"IMvcRazorHost",
description:""
});
y({
url:'/api/Wyam.Common.Util/A109B5B5',
title:"CollectionExtensions",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/7889871B',
title:"MvcRazorHost",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/84EB32EF',
title:"Take",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Html.Abstractions/9BCFE97C',
title:"IHtmlContent",
description:""
});
y({
url:'/api/Wyam.TextGeneration/ECF4453D',
title:"GenerateMeta",
description:""
});
y({
url:'/api/Wyam.Common.IO/E3B246F2',
title:"FilePath",
description:""
});
y({
url:'/api/Wyam.Razor/970BF165',
title:"BaseRazorPage",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/1B25A090',
title:"OtherComment",
description:""
});
y({
url:'/api/Wyam.Images/E4BB1927',
title:"AnchorPosition",
description:""
});
y({
url:'/api/Wyam/F2AE36AE',
title:"InterlockedBool",
description:""
});
y({
url:'/api/Wyam.Common.Configuration/4E5335AA',
title:"ContextConfig",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/497CAEAD',
title:"RazorPageResult",
description:""
});
y({
url:'/api/Wyam.SearchIndex/A3AE5692',
title:"SearchIndex",
description:""
});
y({
url:'/api/Wyam.Tables/B151EC67',
title:"ExcelToCsv",
description:""
});
y({
url:'/api/Wyam.Common.IO/5FDE4AAC',
title:"PathEqualityComparer",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor.Compilation/843EF63B',
title:"RazorFileHash",
description:""
});
y({
url:'/api/Wyam.Core.Documents/C4B39379',
title:"CustomDocument",
description:""
});
y({
url:'/api/Wyam.Yaml/B431AE1F',
title:"Yaml",
description:""
});
y({
url:'/api/Wyam.Less/F6525581',
title:"Less",
description:""
});
y({
url:'/api/Wyam.Common.IO/43DC142F',
title:"PathCollection<TPath>",
description:""
});
y({
url:'/api/Wyam.Owin/2A42A8F0',
title:"ExtensionlessUrlsExtensions",
description:""
});
y({
url:'/api/Wyam.Common.Modules/09D712E1',
title:"IModule",
description:""
});
y({
url:'/api/Wyam.Core/FFC0A751',
title:"TypeHelper",
description:""
});
y({
url:'/api/Wyam.Core.IO.FileProviders.Local/B68D2C25',
title:"LocalFileProvider",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor.Compilation/1F32B39B',
title:"RelativeFileInfo",
description:""
});
y({
url:'/api/Wyam.Minification/E1EAFE5C',
title:"MinifyHtml",
description:""
});
y({
url:'/api/Wyam.Common.Meta/1D453919',
title:"IMetadata",
description:""
});
y({
url:'/api/Wyam.Common.IO/89D2273D',
title:"IReadOnlyFileSystem",
description:""
});
y({
url:'/api/Wyam.SearchIndex/1B44F1C1',
title:"SearchIndexItem",
description:""
});
y({
url:'/api/Wyam.Common.Documents/43457658',
title:"DocumentCollectionExtensions",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/7E3C6467',
title:"Combine",
description:""
});
y({
url:'/api/Wyam.Common.Tracing/36C26D50',
title:"Trace",
description:""
});
y({
url:'/api/Cake.Wyam/B0C05360',
title:"AssemblyNameSettings",
description:""
});
y({
url:'/api/Wyam.Images/74755D00',
title:"ImageFilter",
description:""
});
y({
url:'/api/Wyam/6DEF6B25',
title:"MetadataParseException",
description:""
});
y({
url:'/api/Wyam.Testing.IO/22797376',
title:"StringBuilderStream",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/F76608B2',
title:"OrderBy",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Extensibility/524BCE4B',
title:"Execute",
description:""
});
y({
url:'/api/Wyam/02817FA0',
title:"Program",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/EEE57CCF',
title:"HelperResult",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/EDED0754',
title:"IViewEngine",
description:""
});
y({
url:'/api/Wyam.Common.Documents/4B1BCC2A',
title:"IDocumentFactory",
description:""
});
y({
url:'/api/Wyam.Common.IO/82F6282B',
title:"IFileSystemEntry",
description:""
});
y({
url:'/api/Wyam.Common.IO/ED3E5450',
title:"NormalizedPath",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/EC5E5717',
title:"ViewHierarchyUtility",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/E8D24D15',
title:"ReplaceIn",
description:""
});
y({
url:'/api/Wyam.Common.Meta/58B9208C',
title:"IMetadata<T>",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Metadata/6116E09F',
title:"Tree",
description:""
});
y({
url:'/api/Wyam.Common.Execution/BE745D22',
title:"IPipeline",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/12FFCE52',
title:"RazorViewEngine",
description:""
});
y({
url:'/api/Wyam.Razor/327A28C9',
title:"WyamFileProvider",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/C9F63C9B',
title:"RazorViewFactory",
description:""
});
y({
url:'/api/Wyam.Common.Meta/0BFBB658',
title:"IMetadataValue",
description:""
});
y({
url:'/api/Wyam.Minification/956B8CDC',
title:"MinifierBase",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/E07CEC04',
title:"Download",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/BD9E3958',
title:"ChangeFrequency",
description:""
});
y({
url:'/api/Wyam.Git/89D66CF7',
title:"GitContributors",
description:""
});
y({
url:'/api/Wyam.Common.IO/7C012166',
title:"IDirectory",
description:""
});
y({
url:'/api/Wyam.Common.Meta/70AE72AB',
title:"Keys",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/006ACCBB',
title:"CopyFiles",
description:""
});
y({
url:'/api/Wyam.Configuration.Preprocessing/340DFB7B',
title:"CliSupport",
description:""
});
y({
url:'/api/Wyam.Configuration.Preprocessing/55F33817',
title:"Preprocessor",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor.Compilation/D25DEBC5',
title:"IRazorCompilationService",
description:""
});
y({
url:'/api/Wyam.Common.Caching/7119E3DC',
title:"Crc32",
description:""
});
y({
url:'/api/Wyam.Common.Configuration/9A8399F1',
title:"ConfigExtensions",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/D61FB92D',
title:"ViewStartProvider",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/A5845747',
title:"Sitemap",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Contents/2DD99B48',
title:"Replace",
description:""
});
y({
url:'/api/Wyam.Razor/9711B4AF',
title:"FileInfoExtensions",
description:""
});
y({
url:'/api/Wyam.Common.IO/2CA442EA',
title:"FileEqualityComparer",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/8F5F4B54',
title:"HtmlHelperPartialExtensions",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/2F8159EC',
title:"FrontMatter",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/839A28BC',
title:"IRazorPage",
description:""
});
y({
url:'/api/Cake.Wyam/3DB8CE7C',
title:"AssemblySettings",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Rendering/DF0377A2',
title:"HtmlString",
description:""
});
y({
url:'/api/Wyam.Common.IO/CAB7FF4A',
title:"DirectoryPath",
description:""
});
y({
url:'/api/Wyam.Common.Execution/A4192BB8',
title:"IReadOnlyPipeline",
description:""
});
y({
url:'/api/Wyam.Core.Modules.IO/CE98A0A3',
title:"ReadApplicationInput",
description:""
});
y({
url:'/api/Wyam.Minification/E1389431',
title:"MinifyXhtml",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Control/5197B3C6',
title:"Merge",
description:""
});
y({
url:'/api/Wyam.Core.Configuration/254B4776',
title:"IAssemblyCollection",
description:""
});
y({
url:'/api/Wyam.Core.Modules.Extensibility/044EB768',
title:"Trace",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/5747D05D',
title:"RazorPage",
description:""
});
y({
url:'/api/Wyam.Core.Configuration/CA31916A',
title:"IRawAssemblyCollection",
description:""
});
y({
url:'/api/Wyam.Tables/C9D5D221',
title:"CsvToHtml",
description:""
});
y({
url:'/api/Wyam.Owin/F0489B88',
title:"ExtensionlessUrlsMiddleware",
description:""
});
y({
url:'/api/Wyam.Common.Execution/29BCB760',
title:"IExecutionContext",
description:""
});
y({
url:'/api/Wyam.Common.IO/8C0DBDFE',
title:"IReadOnlyFileProviderCollection",
description:""
});
y({
url:'/api/Wyam.Images/49BDCB6D',
title:"HueInstruction",
description:""
});
y({
url:'/api/Wyam.Configuration.Preprocessing/BAC5064D',
title:"DirectiveValue",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/A0D8F6A4',
title:"ReferenceComment",
description:""
});
y({
url:'/api/Wyam.Testing.Tracing/E0728849',
title:"TestTraceListener",
description:""
});
y({
url:'/api/Wyam/919B9391',
title:"ActionFileSystemWatcher",
description:""
});
y({
url:'/api/Wyam.Razor.Microsoft.AspNet.Mvc.Razor/AFE3977C',
title:"IRazorViewFactory",
description:""
});
y({
url:'/api/Wyam.Testing.IO/333D27D5',
title:"TestDirectory",
description:""
});
y({
url:'/api/Wyam.Testing.IO/EA2C86E7',
title:"TestFileProvider",
description:""
});
y({
url:'/api/Wyam.CodeAnalysis/18381FA3',
title:"AnalyzeCSharp",
description:""
});
y({
url:'/api/Wyam.Common.Modules/5997E918',
title:"IAsNewDocuments",
description:""
});
y({
url:'/api/Wyam.Common.Tracing/79C28BC6',
title:"ITrace",
description:""
});
y({
url:'/api/Cake.Wyam/7792226E',
title:"NuGetSettings",
description:""
});
y({
url:'/api/Wyam.Razor/26B261EF',
title:"Razor",
description:""
});

return {
search: function(q) {return idx.search(q).map(function(i){return idMap[i.ref];});}
};
}();